# Generated by Selenium IDE
from model.group import Group
from fixture.application import Application
import pytest


@pytest.fixture
def app(request):
  fixture = Application()
  request.addfinalizer(fixture.destroy)
  return fixture


def test_add_group(app):

  app.session.login(username="admin", password="secret")
  app.group.create(Group(name="new2", header="new2", footer="new2"))
  app.session.logout()


def test_add_empty_group(app):
  app.session.login(username="admin", password="secret")
  app.group.create(Group(name="", header="", footer=""))
  app.session.logout()


