# Generated by Selenium IDE
from model.group import Group


def test_add_group(app):

  app.session.login(username="admin", password="secret")
  app.group.create(Group(name="new2", header="new2", footer="new2"))
  app.session.logout()


def test_add_empty_group(app):
  app.session.login(username="admin", password="secret")
  app.group.create(Group(name="", header="", footer=""))
  app.session.logout()


