# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from group import Group
from application import Application


class Testaddgroup():
  def setup_method(self, method):
    self.app = Application()
  

  def test_add_group(self):

    self.app.login(username="admin", password="secret")
    self.app.create_group(Group(name="new2", header="new2", footer="new2"))
    self.app.logout()


  def test_add_empty_group(self):
    self.app.login(username="admin", password="secret")
    self.app.create_group(Group(name="", header="", footer=""))
    self.app.logout()


  def teardown_method(self, method):
    self.app.destroy()
